const types = {
  USER: {
    UPDATE: "USER.UPDATE",
    LOGIN: "USER.LOGIN",
    SIGNUP: "USER.SIGNUP",
    LOGINSUCCESS: "USER.LOGINSUCCESS",
    LOGINFAILED: "USER.LOGINFAILED",
    SIGNUPSUCCESS: "USER.SIGNUPSUCCESS",
    SIGNUPFAILED: "USER.SIGNUPFAILED"
  },
  AUTH: {
    OPENSIDEBAR: "AUTH.OPENSIDEBAR",
    CLOSESIDEBAR: "AUTH.CLOSESIDEBAR",
    DOINGAUTH: "AUTH.DOINGAUTH"
  }
};

export default types;
